### ISSUE TITLE
Is this the correct repo for dx.doi.org?

### ISSUE THREAD

**Issue by pcj** [crosscite/citeproc-doi-server#10]
Unsure if I should report a bug with CSL-JSON response from http://dx.doi.org here.  Is this the code that's running that service?  I suspect not.

**Comment by koelnconcert** [comment]
This service (e.g. running at http://crosscite.org/citeproc) is just for formatting CSL-JSON we got from dx.doi.org. The actual CSL-JSON creation is done by each DOI registration agency (e.g. CrossRef or DataCite) individually. 

If you are unsure have a look at the intial URL dx.doi.org is redirecting to when asking for csl, e.g. it's data.datacite.org for DataCite, with sources and tickets here: http://github.com/datacite/content-resolver
