### ISSUE TITLE
prepopulate DOI

### ISSUE THREAD

**Issue by eniad** [crosscite/citeproc-doi-server#16]
Is there a way to pre-populate the DOI in the web form? 

The simple form is great for giving users a way format the citation without us having to host our on code. It would be nice to pre-populate the DOI for them and allow them to decide the style and locale.

If that isn't currently available, could that function be added?

**Comment by mfenner** [comment]
The form is really just a wrapper for a number of APIs. It is very easy to customize this in various ways, e.g. by pre-populating the form. Depending on the specific use case we can pre-populate the existing form with a DOI, or a custom form can be built elsewhere.

What exactly do you want to do?

**Comment by eniad** [comment]
I want to include a link on my a DOI landing pages to the form pre-populate with that DOI.

We already link to the blank form: https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1361
