### ISSUE TITLE
When an apostrophe is part of the creator’s name, the Citation formatter automatically capitalizes the letter following that apostrophe

### ISSUE THREAD

**Issue by kjgarza** [crosscite/citeproc-doi-server#23]
When an apostrophe is part of the creator’s name, the Citation formatter automatically capitalizes the letter following that apostrophe.  You can see this in the APA-style citation generated from the above DOI with “Children’s”:
 
United States Census Bureau, & Children’S Environmental Health Initiative. (2017). American Community Survey (ACS) 2015 data for Harris County, Texas, USA (Version 1) [Data set]. Rice University. https://doi.org/10.25612/837.pnn1zza0va9p
 
… though the problem shows up in all citation styles.  This automatic capitalization is incorrect (the XML file has a lowercase “s”).
 
I tried inputting “&apos;” in the XML file I submit, but DataCite converts it to a single neutral quote ( '  ) ; that’s Unicode character U+0027… so the “s” is still capitalized.
I even tried using U+02BC ( ’ ) (i.e., the slightly curved, typographically-correct apostrophe); though DataCite does not convert it to U+0027, the “s” still remains capitalized.
Could you please fix this issue or let me know if there is a workaround?

**Comment by richardhallett** [comment]
This was fixed within datacite/bolognese#22
