### ISSUE TITLE
BibTeX of "Conference/Talk" in DataCite (RIS-Type: MPCT) is returned as @article

### ISSUE THREAD

**Issue by katrinleinweber** [crosscite/citeproc-doi-server#24]
I tried [obtaining](https://citation.crosscite.org/) the BibTeX of [`10.5446/37829`](https://search.datacite.org/works/10.5446/37829) and a bunch of other [`audiovisual` items in DataCite](https://search.datacite.org/works?query=&resource-type-id=audiovisual) and each are returned as `@article` when I `Select Formatting Style:` `bibtex`.

Where could this issue originate? Here, or Datacite, or @Juris-M's [citeproc-js](https://github.com/Juris-M/citeproc-js/)?

Possibly related to https://github.com/datacite/content-resolver/pull/24#issuecomment-241356577?

**Comment by mfenner** [comment]
@katrinleinweber what type do you expect, `@misc`?

**Comment by katrinleinweber** [comment]
If no better matching item type can be derived/returned, that would certainly be a more logical fall-back than `@article`.

Mostly I was "just" trying to import the metadata of https://av.tib.eu/media/37829 into Zotero. "Write a translator" is already reported to their issue tracker ;-)

**Comment by mfenner** [comment]
bibtex is not a citation style, so I think DOI content negotiation is a better place than the citation formatter service. There is no direct link in DataCite Search, but what you get back (via ) is

```
@misc{https://doi.org/10.5446/37829,
  doi = {10.5446/37829},
  author = {Hammitzsch, Martin},
  keywords = {Information Technology},
  language = {eng},
  title = {Reusability: Software Licensing},
  publisher = {Technische Informationsbibliothek (TIB)},
  year = {2018}
}
```

Which looks as expected to me. Closing the issue.

**Comment by katrinleinweber** [comment]
> bibtex is not a citation style

I wrote `formatting`, see OP. Copy-pasted it from https://citation.crosscite.org/, actually. `bibtex` is in that list, and that's what is generally returned. Just not with `@misc`:

![screen shot 2018-10-18 at 18 48 51](https://user-images.githubusercontent.com/9948149/47170522-80dc8400-d306-11e8-950b-30bdeaf62133.png)

Tried different browsers, of course.

**Comment by mfenner** [comment]
My point was that this is citeproc.js, converting citeproc JSON into bibtex. You can do that, but outside of our control, and not something I recommend, as there is an extra metadata conversion step where you might lose information.

**Comment by mfenner** [comment]
We should remove the bibtex option from the citation formatter.

**Comment by katrinleinweber** [comment]
> My point was that this is citeproc.js, converting citeproc JSON into bibtex.

https://data.datacite.org/application/vnd.citationstyles.csl+json/10.5446/37829 already contains `article`. https://data.datacite.org/application/vnd.schemaorg.ld+json/10.5446/37829 looks correct.

**Comment by mfenner** [comment]
As I said, the additional metadata conversion can be an issue. We map directly from DataCite XML to bibtex in our content negotiation. One reason citeproc json uses `article` is that this is the fallback option for citation styles.

**Comment by mfenner** [comment]
To complicate matters, we have started to use citeproc-ruby instead of citeproc.js in some places last week (not yet data.datacite.org).
