### ISSUE TITLE
CORS header is broken

### ISSUE THREAD

**Issue by lizkrznarich** [crosscite/citeproc-doi-server#32]
HTTP response header configuration in https://github.com/crosscite/citeproc-doi-server/blob/32399314aa9cfe1aa488399e37529c4d7cd8e224/vendor/docker/webapp.conf#L12 is not formatted correctly, which is breaking CORS access.

Headers are formatted as ```add_header 'Access-Control-Allow-Origin: *' always;```

Per NGINX docs, headers should be formatted as 
```add_header name value [always];``` http://nginx.org/en/docs/http/ngx_http_headers_module.html

<img width="562" alt="Screen Shot 2021-12-02 at 2 57 21 PM" src="https://user-images.githubusercontent.com/8026886/144505735-fc926de5-5ab8-4ce5-9cca-95d57ea66dc3.png">

**Comment by alan-wu** [comment]
#33  has fixed the CORS issue I was experiencing on the request to citation.crosscite.org, thank you.
