### ISSUE TITLE
Incorrectly formatted author list in bibtex citation

### ISSUE THREAD

**Issue by lnielsen** [crosscite/citeproc-doi-server#9]
@moorepants reported to @zenodo that the author list in bibtex is incorrectly formatted. @zenodo is using the DOI Citation Formatter (http://crosscite.org/citeproc/) which I believe is based on this project. Specifically the authors should be separated by `` and ``, and the keys contains e.g. comma. 

**Example**

http://crosscite.org/citeproc/format?style=bibtex&doi=10.5281/zenodo.11579:
```
@misc{Christopher Dembia, Jason K. Moore_2014, 
    title={yeadon-1.2.0}, 
    url={http://dx.doi.org/10.5281/zenodo.11579}, 
    DOI={10.5281/zenodo.11579}, 
    publisher={ZENODO}, 
    author={Christopher Dembia, Jason K. Moore}, 
    year={2014}
}
```

and here I assume the formatting is based on http://data.datacite.org/application/vnd.citationstyles.csl+json/10.5281/zenodo.11579:
```json
{
    type: "misc",
    DOI: "10.5281/zenodo.11579",
    URL: "http://dx.doi.org/10.5281/zenodo.11579",
    title: "yeadon-1.2.0",
    publisher: "ZENODO",
    issued: {
        raw: "2014"
    },
    author: [
        {literal: "Christopher Dembia"},
        {literal: "Jason K. Moore"}
    ]
}
```

As far as I can see from https://github.com/citation-style-language/styles/blob/master/bibtex.csl#L84 it should be using `` and `` as separator between authors, so what can the issue be?

**Comment by mfenner** [comment]
Fixed by https://github.com/datacite/content-resolver/issues/28.
